[fixbug] change conversion to appunit from float of percentage calcuation
servo/stylo pull request #102
Opened 2024-12-26 02:54 UTC by Asun0204

change conversion to appunit from float of percentage calcuation, prevent child box size is calculated too large.

2025-01-08 14:01 UTC, Loirooriol commented
Since we want to test this before publishing a new release of app units, let's inline the code here for now.

2025-01-08 14:02 UTC, Loirooriol commented
BTW, when creating a PR it's better not to use your main branch.

2025-01-08 14:49 UTC, Loirooriol reviewed
It may make more sense to modify this instead: https://github.com/servo/stylo/blob/7e529e8cf99502c99e431515de095d18548219d5/style/values/computed/length.rs#L496-L501

I thought that would be more likely to affect Firefox, but I have tried commenting that (and its callers) out, and Firefox compiles fine, so it's not used.

2025-02-10 03:36 UTC, Asun0204 commented
I'm sorry about the code you commit is overwitten by mistake, can you push the code again? @Loirooriol

2025-02-10 06:57 UTC, Loirooriol commented
What code, https://github.com/servo/stylo/commit/83dad258d1a64a88a30468751774dec2169ebe67 ?

2025-02-10 07:40 UTC, Loirooriol commented
Sure, you can try that. But currently the logic first resolves LengthPercentage into a Length and then to an Au. You will need to remove the middle step.

2025-02-11 11:58 UTC, Asun0204 commented
> Sure, you can try that. But currently the logic first resolves LengthPercentage into a Length and then to an Au. You will need to remove the middle step.

I don't known how to remove the middle step. Do I need to copy the percenrage calculation in `maybe_to_used_value`? And it will skip normallized operation provided by Length.

2025-02-11 13:57 UTC, Loirooriol commented on style/values/computed/length_percentage.rs
> +        if let Unpacked::Percentage(_) = self.unpack() {
Probably `Unpacked::Calc` should truncate too.

2025-02-18 12:53 UTC, Loirooriol commented on style/values/computed/length_percentage.rs
> +        if let Unpacked::Percentage(_) = self.unpack() {
Rounding for `calc()` is better according to https://phabricator.services.mozilla.com/D202746

2025-02-19 03:07 UTC, Asun0204 commented on style/values/computed/length_percentage.rs
> +        if let Unpacked::Percentage(_) = self.unpack() {
The workflow that I just change the percenrage method using truncate has been passed. So should we merge app_units pr? Then the stylo pr could be merged. And do we need to modify the version?
https://github.com/Asun0204/servo/actions/runs/13385320860

2025-03-03 09:11 UTC, Asun0204 commented
@Loirooriol The code is completed according to the solution discussed. Can you review the code again?

https://github.com/servo/stylo/pull/102
https://github.com/servo/app_units/pull/60

2025-03-03 09:29 UTC, Loirooriol commented
Update the Servo PR as requested: https://github.com/servo/servo/pull/34714#pullrequestreview-2641154294

2025-03-04 09:19 UTC, Loirooriol requested changes
Don't revert e2c385d

2025-03-04 13:04 UTC, Loirooriol requested changes
The PR is still including unrelated commits.

2025-03-04 13:17 UTC, Loirooriol commented
Remove https://github.com/servo/stylo/pull/102/commits/f588e855d77ba5ebc6ced99247b3163427f8c8b6

2025-03-04 13:24 UTC, Loirooriol commented
You need to rebase your changes on top of the latest `main` (0190fff).

2025-03-04 13:38 UTC, Asun0204 commented
I completed it. There is only one commit base on the latest main.

2025-03-04 13:56 UTC, Asun0204 commented on style/values/computed/length_percentage.rs
> +                .map(|length| Au::from_f32_px_trunc(length.px()));
I push a commit to import app_units pr for compiling it.
It's ok now.

2025-03-05 00:38 UTC, Loirooriol commented on style/values/computed/length_percentage.rs
> +        self.maybe_percentage_relative_to(container_len.map(Length::from)).map(Au::from)
No need to repeat `self.maybe_percentage_relative_to(container_len.map(Length::from))`

```suggestion
        self.maybe_percentage_relative_to(container_len.map(Length::from))
            .map(if let Unpacked::Percentage(_) = self.unpack() {
                |length| Au::from_f32_px_trunc(length.px())
            } else {
                Length::from
            })
    }
```

2025-03-05 00:51 UTC, Loirooriol requested changes
Also you should cover `to_used_value` for consistency.

2025-03-05 06:39 UTC, Asun0204 commented on style/values/computed/length_percentage.rs
> +        self.maybe_percentage_relative_to(container_len.map(Length::from)).map(Au::from)
fixed.

2025-03-06 06:37 UTC, Asun0204 commented on style/values/computed/length_percentage.rs
>          Au::from(self.to_pixel_length(containing_length))
fixed

2025-03-11 11:01 UTC, Loirooriol commented
You keep using "calcuation" instead of "calculation".
But just avoid this word since it seems to refer to `calc()` and this is about plain percentages.
Also "float of percentage" is confusing.

2025-03-11 21:10 UTC, merged